# encoding: utf-8
"""
Django settings for opsweb project.

Generated by 'django-admin startproject' using Django 1.8.18.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lp-fg_+n1$e+93)szwq7zu8od)%_5i+qytuhg&lqa1(_u$nb(_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'dashborad',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'opsweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opsweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#         'NAME': 'ops',
#         'USER': 'xie',
#         'PASSWORD': 'Fs9006',
#         'HOST': '192.168.44.132',
#         'PORT': 3306
#         }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#         'NAME': 'ops',
#         'USER': 'xie',
#         'PASSWORD': 'Fs9006',
#         'HOST': '192.168.254.191',
#         'PORT': 3306
#         }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': 'k8s',
        'USER': 'woniu',
        'PASSWORD': '123456',
        'HOST': '192.168.254.191',
        'PORT': 3306
        }
}

# mysql -uwoniu -p123456
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
# 斜杠
# APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# yemiantiaozhuan moban
TEMPLATE_JUMP = 'public/jump.html'
TEMPLATE_403 = '/permissions/none'
LOGGING = {
    'version': 1,
    'loggers': {
        'opsweb': {
            'level': 'DEBUG',
            'handlers': ['console_handle', 'file_handlers']
        },
        'django': {
            'level': 'DEBUG',
            'handlers': ['dj_file_handlers']
        }
        # 'django.request': {
        #     'level': 'DEBUG',
        #     'handlers': ['dj_re_handlers']
        # }
    },
    'handlers': {
        'console_handle': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_handlers': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'ops.log'),
            'formatter': 'opsweb'
        },
        'dj_file_handlers': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'dj.log'),
            'formatter': 'opsweb'
        },
        'dj_re_handlers': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 're.dj.log'),
            'formatter': 'opsweb'
        }
    },
    'formatters': {
       'opsweb': {
           'format': '%(asctime)s - %(pathname)s:%(lineno)d[%(levelname)s] - %(message)s'
       },
        'simple': {
            'format': '%(asctime)s - %(levelname)s - %(message)s'
        }
    },
    'root': {
        'level': 'DEBUG',
        'handles': ['console_handle']
    }
}

LOGIN_URL = '/login/'
